import {Web3Provider} from "../configs";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
      <Web3Provider>{children}</Web3Provider>
    </body>
    </html>
  )
}
